---
title: "pathway related analysis with MaAsLin on Sinha dataset"
author: "Jimmy Zhong"
date: "7/15/2022"
output: html_document
---

```{r setup, include=FALSE}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path ))
source("./init_share.R")
```

```{r}
raw = read_csv("../MAG_pnps_redux/signalCAZyme-abun-vs-genes-pnps.csv")
raw["ocean"] = str_split_fixed(raw$bin, fixed("-"), 2)[, 1]
raw = filter(raw, (!is.na(defense_count) & (!is.na(scg_count))))

fudge_CAZ = min(raw$signal_CAZyme_abun[raw$signal_CAZyme_abun>0])
fudge_def = min(raw$defense_pnps_median[raw$defense_pnps_median>0])
fudge_scg = min(raw$scg_pnps_median[raw$scg_pnps_median>0])

raw$defense_pnps_median = raw$defense_pnps_median + fudge_def
raw$scg_pnps_median = raw$scg_pnps_median + fudge_scg

CAZyme_defense = raw %>%
  filter(defense_count >= 11) %>%
  filter(scg_count >= 11) %>%
  mutate(depth = factor(depth, levels = c("SRF","DCM","MES","deep"))) %>%
  mutate(norm_sigCAZ =
     ifelse(signal_CAZyme_abun <= 0,fudge_CAZ,signal_CAZyme_abun+fudge_CAZ))%>%
  mutate(log_signal_CAZ = log(norm_sigCAZ)) %>%
  mutate(log_median_defense_pnps = log(defense_pnps_median)) %>%
  mutate(def_scg_ratio = defense_pnps_median/scg_pnps_median) %>%
  mutate(log_def_scg_ratio = log10(def_scg_ratio))

CAZyme_defense %>%
  filter(log_signal_CAZ > -9) %>%
  filter(def_scg_ratio < 3.26) %>% # outliers
  filter(ocean %in% c("IN","NP","SP","NAT","SAT")) %>%
  # filter(!ocean %in% c("MED", "EAC", "RS")) %>%
  ggplot(aes(x=log_signal_CAZ, y=defense_pnps_median/scg_pnps_median)) +
  geom_point(alpha = 0.2) +
  geom_smooth(method = "lm")+
  facet_wrap(~depth, scale = "free")

CAZyme_defense %>%
  filter(log_signal_CAZ > -10) %>%
  filter(ocean %in% c("IN","NP","SP","NAT","SAT")) %>%
  ggplot(aes(x=log_signal_CAZ, y=log_def_scg_ratio)) +
  geom_point(alpha = 0.2) +
  geom_smooth(method = "lm")+
  facet_grid(depth~ocean, scale = "free")

summary(lm(log_def_scg_ratio~depth + ocean + log_signal_CAZ, 
           data = CAZyme_defense %>%
             filter(log_signal_CAZ > -9)))


greatest16 = as.data.frame(sort(table(CAZyme_defense$bin), decreasing = TRUE)[1:16])$Var1

CAZyme_defense %>%
  filter(bin %in% greatest16) %>%
  ggplot(aes(x=log_signal_CAZ, y=log_median_defense_pnps)) +
  geom_point() +
  geom_smooth(method = "lm")+
  facet_wrap(~bin, scale = "free")

CAZ.defense.lm = lm(log_median_defense_pnps~log_signal_CAZ,
                    filter(CAZyme_defense, depth == "MES"))
```



```{r}
raw = read_csv("../MAG_pnps_redux/signalCAZyme-abun-vs-genes-pnps.csv")
raw["ocean"] = str_split_fixed(raw$bin, fixed("-"), 2)[, 1]
raw = filter(raw, (!is.na(transposase_count) & (!is.na(scg_count))))

fudge_trans = min(raw$transposase_pnps_median[raw$transposase_pnps_median>0])

raw$transposase_pnps_median = raw$transposase_pnps_median + fudge_def
raw$scg_pnps_median = raw$scg_pnps_median + fudge_scg

CAZyme_transposase = raw %>%
  filter(transposase_count >= 5) %>%
  filter(scg_count >= 11) %>%
  mutate(depth = factor(depth, levels = c("SRF","DCM","MES","deep"))) %>%
  mutate(norm_sigCAZ =
     ifelse(signal_CAZyme_abun <= 0,fudge_CAZ,signal_CAZyme_abun+fudge_CAZ))%>%
  mutate(log_signal_CAZ = log(norm_sigCAZ)) %>%
  mutate(log_median_trans_pnps = log(transposase_pnps_median)) %>%
  mutate(log_def_scg_ratio = log10(transposase_pnps_median/scg_pnps_median))

CAZyme_transposase %>%
  filter(log_signal_CAZ > -9) %>%
  # filter(ocean %in% c("IN","NP","SP","NAT","SAT")) %>%
  # filter(!ocean %in% c("MED", "EAC", "RS")) %>%
  ggplot(aes(x=log_signal_CAZ, y=log_def_scg_ratio)) +
  geom_point(alpha = 0.2) +
  geom_smooth(method = "lm")+
  facet_wrap(~depth, scale = "free")

```




```{r}
pnps_melt = function(pnps_df, select_col){
  return( reshape2::melt(pnps_df[select_col], id =c("bin"), value.name = c("diff")) )
}

g(defense_df, toxin_df, indi_toxin_df, GOC_toxin_df, mobilome_df, trans_df) %=% init_MAGs_pnps_depths()


sel=c("bin","gene_callers_id","SRF_ratio", "DCM_ratio", "MES_ratio", "BAT_ratio")
viz = reshape2::melt(indi_toxin_df[sel], id =c("bin","gene_callers_id"), value.name = c("diff"))
viz$cat = paste(viz$bin, viz$gene_callers_id)
viz %>%
  filter(grepl("NAT",bin)) %>%
  filter(diff < 0.2 & diff > -0.2) %>%
  ggplot(aes(x=variable, y=diff))+
  # geom_boxplot(outlier.shape = NA)+
  geom_point(aes(colour = cat), alpha = 0.3)+
  geom_line(aes(group = cat), alpha = 0.2) +
  theme_classic()


sel = c("bin", "SRF_ratio", "DCM_ratio", "MES_ratio", "BAT_ratio")
pnps_melt(toxin_df, sel) %>%
  # mutate(log_diff = log10(diff+10)) %>%
  # filter(log_diff < 1.01 & log_diff > 0.99) %>%
  filter(diff < 0.3 & diff > -0.3) %>%
  ggplot(aes(x=variable, y=diff))+
  # geom_boxplot(outlier.shape = NA)+
  geom_point(aes(colour=bin), alpha = 0.3)+
  geom_line(aes(group = bin, color = bin), alpha = 0.5) +
  theme_classic()
  # theme(legend.position="none")
```

```{r}
toxin = read_csv("../toxin-db/all_oceans_toxin_pnps_per_sample.csv",
                 col_types = cols(toxin_median = col_double(),
                                  bin_median = col_double()))
toxin = toxin %>% 
  filter(!depth == "depth") %>%
  mutate(depth = factor(depth, levels = c("SRF", "DCM", "MES", "deep"))) %>%
  separate(col = cat, into = c("bin", "sample"), sep = ":")

toxin$ratio = log(toxin$toxin_median) - log(toxin$bin_median)

toxin %>%
  filter(ratio < 2 & ratio > -2) %>%
  ggplot(aes(x = depth, y = ratio)) +
  geom_boxplot() +
  geom_point(aes(colour=bin), alpha = 0.3)+
  geom_line(aes(group = bin, color = bin), alpha = 0.5) +
  theme(legend.position="none")

toxin %>%
  filter(toxin_median < 1) %>%
  ggplot(aes(x = depth, y = bin_median)) +
  geom_boxplot() +
  # geom_point(aes(colour=bin), alpha = 0.3)+
  # geom_line(aes(group = bin, color = bin), alpha = 0.5) +
  theme(legend.position="none")

```












