---
title: "Analyzing pnps of integron contigs in MAGs"
author: "Jimmy Zhong"
date: "7/21/2022"
output: html_document
---

```{r setup, include=FALSE}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path ))
source("./init_share.R")
init_env()
```

```{r}
raw = read_csv("../MAG_pnps_redux/MAG_integron_pnps_all_v2.csv")

raw2 = raw %>%
  filter(total_count > 20) %>%
  mutate(depth = factor(depth, levels = rev(c("SRF","DCM","MES","deep"))),
         norm_pnps = pnps/scg_pnps_median) %>%
  filter(norm_pnps < 10) %>%
         # norm_pnps = pnps/scg_pnps_median) %>%
  mutate(has_fun = ifelse(COG_accession == "nan", "no", "yes"),
    type = ifelse( COG_accession == "nan", "no\nfunction",
           ifelse( grepl("V", COG_accession), "defense",
           # ifelse( grepl("T", COG_accession), "signal T", 
           "other COG")))

raw2 %>%
  # filter(COG_accession != "nan") %>%
  ggplot(aes(y=type,
             x=sqrt(norm_pnps))) +
  geom_boxplot(outlier.shape = NA) +
  # xlab("pnps ratio of cassette genes in MAGs") +
  # facet_wrap(~depth) +
  geom_point(alpha = 0.2) +
  stat_summary(fun.data = boxplot.give.nr, 
               geom = "text", position=position_nudge(x = 0.05, y = 0.15))

tmp1 = raw2[raw2$type == "defense",]
tmp2 = raw2[raw2$type == "other COG",]
wilcox.test(tmp1$pnps, tmp2$pnps)


integrons = filter(raw, (!is.na(defense_count) & (!is.na(scg_count))))
fudge_def = min(integrons$defense_pnps_median[integrons$defense_pnps_median>0])
fudge_scg = min(integrons$scg_pnps_median[integrons$scg_pnps_median>0])
fudge_pnps = min(integrons$pnps[integrons$pnps>0])

integrons$defense_pnps_median = integrons$defense_pnps_median + fudge_def
integrons$scg_pnps_median = integrons$scg_pnps_median + fudge_scg
# integrons$pnps = integrons$pnps + fudge_pnps

integrons = integrons %>% 
  # filter(integron %in% c("complete","CALIN")) %>%
  filter(scg_count >= 11) %>%
  mutate(ratio_of_pnps = pnps/scg_pnps_median) %>%
  mutate(sqrt_ratio = sqrt(ratio_of_pnps)) %>%
  mutate(log_ratio = log((pnps + fudge_pnps)/scg_pnps_median))


integrons %>%
  # filter(integron %in% c("complete","CALIN")) %>%
  filter(ratio_of_pnps < 15) %>%
  ggplot(aes(y=is_defense, x=sqrt_ratio)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(alpha = 0.2) +
  stat_summary(fun.data = boxplot.give.nr, 
               geom = "text", position=position_nudge(x = 0.3, y = 0.15))

wilcox.test(ratio_of_pnps~is_defense,integrons)
wilcox.test(pnps~is_defense, raw)
```


```{r}
rank = read_csv("../MAG_pnps_redux/MAG_integron_pnps_rank.csv")
rank2 = rank %>%
  filter(total_pnps > 101) %>%
  mutate(percentile = rank/total_pnps * 100,
    type = ifelse( is.na(COG_accession), "other COG",
           ifelse( grepl("V", COG_accession), "defense",
           "other COG")))

rank2 %>%
  ggplot(aes(x=percentile)) +
  facet_wrap(~COG_category, scales = "free_y") +
  geom_histogram(binwidth=8)
```

