---
title: "Particle associated lifestyle and genome size and depths of MAGs"
author: "Jimmy Zhong"
date: "8/16/2022"
output: html_document
---

```{r setup, include=FALSE}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path ))
source("./init_share.R")
g(all_MAGs, low_trans, high_trans) %=% init_bins()
all_MAGs = merge_MAGs_CAZyme_peptide(all_MAGs)
MAGs_p = filter(all_MAGs, eukarya_prop < 0.05 & depth != "MIXED")

bi_depth = c("Shadow (SRF, DCM)", "Deep (MES, BAT)")

MAGs_p = MAGs_p %>% mutate(
  trans_fudge = percent_trans + get.fudge(MAGs_p, "percent_trans"),
  log_percent_trans = log(trans_fudge),
  log_sect_CAZ = log(percent_sect_CAZ + get.fudge(MAGs_p, "percent_sect_CAZ")),
  log_sect_pep = log(percent_sect_pep + get.fudge(MAGs_p, "percent_sect_CAZ")),
  log_genome_size = log(complete_genome_size),
  is_deep = ifelse(depth %in% c("SRF", "DCM"), bi_depth[1], bi_depth[2])
) %>%
  mutate(is_deep = factor(is_deep, levels = bi_depth))
```

```{r}
t.obj = t.test(log_genome_size~is_deep, MAGs_p)

1/exp(t.obj$conf.int)
```

## Spearman correlation in each depth
```{r}
get.depth.trans.corr = function(xvar, yvar = "percent_trans"){
  tmp = MAGs_p[c("is_deep", xvar, yvar)]
  colnames(tmp) = c("depth", "var1", "var2")
  tmp %>%
    group_by(depth)%>%
    summarize(p.val = suppressWarnings(cor.test(var1, var2, method = "spearman")$p.val),
      estimate = suppressWarnings(cor.test(var1, var2, method = "spearman")$estimate),
      count = n()) %>%
    adjust_pvalue(method = "BH") %>%
    as.data.frame()
}

cor.test(MAGs_p$percent_trans, MAGs_p$percent_sect_CAZ, method = "spearman")
cor.test(MAGs_p$percent_trans, MAGs_p$percent_sect_pep, method = "spearman")

get.depth.trans.corr("complete_genome_size")

depth.CAZ = get.depth.trans.corr("percent_sect_CAZ")
depth.pep = get.depth.trans.corr("percent_sect_pep")
sel = c("depth", "count", "p.val", "estimate")
merge.CAZpep = merge(depth.CAZ[sel], depth.pep[sel], by = c("depth", "count"))
```

```{r}
get.depth.trans.corr(xvar = "percent_sect_CAZ", yvar = "complete_genome_size")
get.depth.trans.corr(xvar = "percent_sect_pep", yvar = "complete_genome_size")
```

## addition of models
```{r}
MAGs_p.s = MAGs_p[!is.na(MAGs_p$percent_sect_pep), ]
MAGs_p.s$Class[is.na(MAGs_p.s$Class)] = "others"

depth.lm = lm(log_percent_trans~depth, data=MAGs_p.s)
depth.gz.lm = update(depth.lm, .~. + log_genome_size)
depth.CP.lm = update(depth.lm, .~. + log_sect_CAZ + log_sect_pep)
depth.CP.gz.lm = update(depth.CP.lm, .~. + log_genome_size)
depth.CP.gz.tax.lm = update(depth.CP.gz.lm, .~. + Class)

get.lm.stats = function(lm1, lm2) {
  F.val = anova(lm1, lm2)$`Pr(>F)`[2]
  r.sqrt = get_r(lm2)
  return(c(F.val, r.sqrt))
}

get_r(depth.lm)
get.lm.stats(depth.lm, depth.gz.lm)

anova(depth.CP.gz.lm, depth.gz.lm)
anova(depth.lm, update(depth.lm, .~. + Class))

summary(update(depth.lm, .~. + log_sect_pep))
summary(update(depth.lm, .~. + log_sect_CAZ))
summary(update(depth.lm, .~. + log_genome_size))
summary(update(depth.lm, .~. + Class))
```

```{r}
r.sqrt = c(get_r(depth.lm), get_r(depth.C.lm), 
  get_r(depth.CP.lm), get_r(depth.CP.gz.lm), get_r(depth.CP.gz.tax.lm))

shapiro.test(resid(depth.CP.gz.tax.lm))
reg.aov = as.data.frame(anova(depth.CP.gz.tax.lm)[1:5, ])

explain.var = c("Depth", "Secretory CAZyme (%)",
"Secretory Peptidase (%)", "Complete Genome Size (Mbp)", "Taxonomy (Class)")

rownames(reg.aov) = explain.var
reg.aov['idx'] = explain.var

reg.aov2 = reg.aov[c("idx", "Pr(>F)")]
# reg.aov2$`Sum Sq` = round(reg.aov2$`Sum Sq`, 2)
reg.aov2$`Pr(>F)` = ifelse(reg.aov2$`Pr(>F)` < 0.00001, "< 1e-10", 
                           round(reg.aov2$`Pr(>F)`, 5))

colnames(reg.aov2) = c("Explanatory Variables", "P for F-test")

reg.aov2$`Cumulative R^2` = round(r.sqrt, 3)

write.csv(reg.aov2, file = "out/Table1-MAGs-reg.csv", row.names = FALSE)
write.csv(reg.aov2, file = paste0(googleDrive.loc, "/Table1-MAGs-reg-raw.csv"),
          row.names = FALSE)
```

## per-taxon per-depth particle association V2
```{r}
id.var = c("Class", "depth")

get.taxa.cor = function(MAGs.df, var1, var2) {
  tmp = MAGs.df[c(id.var, var1, var2)]
  colnames(tmp) = c(id.var, "var1", "var2")
  
  reg.res = tmp %>%
    group_by(Class, depth) %>%
    summarize(count = n(),
      p.val = suppressWarnings(cor.test(var1, var2, method = "spearman")$p.val),
      est = suppressWarnings(cor.test(var1, var2, method = "spearman")$estimate)) %>%
    adjust_pvalue(method = "BH") %>%
    add_significance()
  
  per.var = c("est", "p.val.adj", "p.val.adj.signif")
  per.var2 = paste0(paste0(var1, ".", var2), ".corr")
  
  out.res = reg.res[c(id.var, per.var)]
  out.res = out.res %>%
    mutate(est = ifelse(p.val.adj < 0.05, 
                        paste0(round(est, 3), p.val.adj.signif),
                        p.val.adj.signif))
  
  out.res = out.res[c(id.var, "est")]
  colnames(out.res) = c(id.var, per.var2)
  return(out.res)
}

MAG.big.taxa = MAGs_p %>%
  filter(!is.na(Class)) %>%
  group_by(Class, depth) %>%
  mutate(n = n(),
         gsize = complete_genome_size,
         transposase = percent_trans,
         CAZyme = percent_sect_CAZ,
         peptidase = percent_sect_pep) %>%
  filter(n >= 12)

MAG.stat.base = MAG.big.taxa %>%
  group_by(Class, depth) %>%
  summarize(count = n(),
            `mean CAZyme (%)` = round(mean(CAZyme),2),
            `mean peptidase (%)` = round(mean(peptidase),2))

CAZ.gs.stats = get.taxa.cor(MAG.big.taxa, "CAZyme", "gsize")
pep.gs.stats = get.taxa.cor(MAG.big.taxa, "peptidase", "gsize")

CAZ.trans.stats = get.taxa.cor(MAG.big.taxa, "CAZyme", "transposase")
pep.trans.stats = get.taxa.cor(MAG.big.taxa, "peptidase", "transposase")

tmp = merge(MAG.stat.base, CAZ.gs.stats, by = id.var)
tmp = merge(tmp, pep.gs.stats, by = id.var)
tmp = merge(tmp, CAZ.trans.stats, by = id.var)
MAG.stat.full = merge(tmp, pep.trans.stats, by = id.var)
MAG.stat.full = MAG.stat.full %>%
  mutate(depth = factor(depth, levels = c("SRF", "DCM", "MES", "BAT"))) %>%
  arrange(Class, depth)

write.csv(MAG.stat.full,"out/per-class-depth-sect-gsize-corr.csv", row.names = FALSE)
```

## Are CAZyme peptidase different in MAGs taxon across depth?
```{r}
get.diff = function(MAG.df, taxon, var) {
  tmp = MAG.df[MAG.df$Class == taxon, ]
  tmp['var'] = tmp[var]
  aov.res = aov(var~depth, data = tmp)
  print(multcompView::multcompLetters(TukeyHSD(aov.res)$depth[,4])$Letters)
}

get.diff(MAGs_p, "Acidimicrobidae", "percent_sect_CAZ")
get.diff(MAGs_p, "Acidimicrobidae", "percent_sect_pep")

get.diff(MAGs_p, "Alphaproteobacteria", "percent_sect_CAZ")
get.diff(MAGs_p, "Alphaproteobacteria", "percent_sect_pep")

get.diff(MAGs_p, "Flavobacteria", "percent_sect_CAZ")
get.diff(MAGs_p, "Flavobacteria", "percent_sect_pep")

get.diff(MAGs_p, "Gammaproteobacteria", "percent_sect_CAZ")
get.diff(MAGs_p, "Gammaproteobacteria", "percent_sect_pep")

get.diff(MAGs_p, "Verrucomicrobia", "percent_sect_CAZ")
get.diff(MAGs_p, "Verrucomicrobia", "percent_sect_pep")
```

# which taxa class is transposase enriched?

```{r}
MAGs.t = MAGs_p
MAGs.t$Class[is.na(MAGs.t$Class)] = "other"
# MAGs.t = MAGs_p[MAGs.t$Class != "other", ]

big_taxa = MAGs.t %>% 
  group_by(Class) %>%
  summarise(count = n()) %>%
  filter(count >= 10) %>%
  drop_na()

out.df = data.frame()
for (taxa in big_taxa$Class){
  cur = MAGs.t[MAGs.t$Class==taxa, 'trans_fudge']
  other = MAGs.t[MAGs.t$Class!=taxa, 'trans_fudge']
  res = suppressWarnings(wilcox.test(cur, other))
  direction = "more"
  if (median(cur) < median(other)){
    direction = "less"
  }
  row = c(taxa, res$p.value, direction)
  out.df = rbind(out.df, row)
}

colnames(out.df) = c("class", "p.value", "direction")

adjust_pvalue(out.df) %>%
  arrange(direction) %>%
  filter(p.value.adj < 0.05)
```

