---
title: "pathway related analysis with MaAsLin on Sinha dataset"
author: "Jimmy Zhong"
date: "7/15/2022"
output: html_document
---

```{r setup, include=FALSE}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path ))
source("./init_share.R")
all_MAGs = init_bins()
MAGs.p = filter(all_MAGs, eukarya_prop < 0.05 & depth != "MIXED")
MAGs.p$trans_fudge = MAGs.p$percent_trans + get.fudge(MAGs.p, "percent_trans")

scg_trans = read_csv("../MAG_pnps_redux/transposase-abun-vs-scg-pnps.csv")
scg_trans$MAG_pnps_median = scg_trans$MAG_pnps_median + get.fudge(scg_trans, "MAG_pnps_median")
```

## Take only the depth that a MAG is in

This is the bottom graph
```{r}
id.col = c("bin", "depth")
MAGs.col = c(id.col, "Class", "trans_fudge", "percent_trans")
pnps.col = c(id.col, "total_count", "MAG_pnps_median", "scg_pnps_median")

tmp = scg_trans[pnps.col]
tmp$depth = gsub("deep", "BAT", tmp$depth)
tmp$bin = gsub("deep-", "deep_MAG_", tmp$bin)

pnps.match = merge(MAGs.p[MAGs.col], tmp, by = id.col)

# pnps.class.match = pnps.match %>% group_by(Class) %>%
#   summarise(mean_trans = mean(percent_trans),
#             median_pnps = median(scg_pnps_median))
# 
# View(pnps.class.match)
# 
# plot(log(mean_trans) ~ log(median_pnps), pnps.class.match)

pnps.match$depth = factor(pnps.match$depth, c("SRF","DCM","MES","BAT"))
pnps.cutoff = quantile(pnps.match$MAG_pnps_median, 0.95) # 0.427

pnps.g = pnps.match %>%
  filter(total_count >= 100 & MAG_pnps_median < pnps.cutoff)

y.limits = c(0.9 * min(pnps.g$trans_fudge), 1.1 * max(pnps.g$trans_fudge))

pnps.a = pnps.g %>%
  ggplot(aes(x = MAG_pnps_median, y = trans_fudge)) +
  facet_wrap(~depth) +
  scale_y_continuous(limits = y.limits, trans = "log10") +
  theme_bw() +
  stat_cor(method = "spearman", cor.coef.name = "rho") +
  geom_smooth(method = "lm", se = T, color = "orange") +
  geom_point(alpha = 0.3, size = 1) +
  labs(x = "MAG median *pN/pS*",
       y = "transposase ORF in MAGs (%)") +
  theme(axis.title.x = ggtext::element_markdown(),
        axis.text.x = element_text(color="black"),
        axis.text.y = element_text(color="black"))
```

## The top graph
```{r}
pnps.match2 = pnps.g %>%
  mutate(depth = fct_rev(depth))

depth.t = table(pnps.match2$depth)
MAGs.t = table(unique(pnps.g[id.col])$depth)
depth.str = as.character(pnps.match2$depth)
depth.counts = paste0("    ", depth.str, " (n = ", depth.t[depth.str],
                     ", ", MAGs.t[depth.str], " MAGs)")
pnps.match2$depth = depth.counts
depth.c = unique(depth.counts)

aov.res = aov(MAG_pnps_median~depth, data = pnps.match2)
letters.df = data.frame(multcompView::multcompLetters(TukeyHSD(aov.res)$depth[,4])$Letters)
colnames(letters.df)[1] = "Letter"
letters.df$depth = rownames(letters.df)
placement = pnps.match2 %>%
  group_by(depth) %>%
  summarise(y.pos = quantile(MAG_pnps_median)[4])

letters.df = left_join(letters.df, placement) 

pnps.b = pnps.match2 %>%
  mutate(depth = factor(depth, levels = c(depth.c[4], depth.c[1], depth.c[2], depth.c[3]))) %>%
  ggplot(aes(y = MAG_pnps_median, x = depth)) +
  geom_boxplot(alpha = 0.3) +
  geom_text(data = letters.df, aes(x = depth, y = y.pos, label = Letter),
            size = 4, color = "black", hjust = -1, vjust = -0.4) +
  labs(y = "MAG median *pN/pS*") +
  coord_flip() +
  theme_classic() +
  theme(axis.title.x = ggtext::element_markdown(),
        axis.text.x = element_text(color="black"),
        axis.text.y = element_text(color="black"),
        axis.title.y = element_blank())

# ggarrange(pnps.b, pnps.a, ncol = 1, heights = c(1,2.8),
#           labels = c("A", "B"))
# 
# ggsave("out/F4_MAG-trans-median-pnps.pdf",
#        height = 6, width = 5)
# 
# ggsave(paste0(googleDrive.loc, "/Figure4_MAG-trans-median-pnps.pdf"),
#        plot = last_plot(), height = 6, width = 5)
```  

## filter out 0% transposase test
```{r}
min_trans = min(pnps.g$trans_fudge)
pnps.g %>%
  filter(trans_fudge > min_trans) %>%
  group_by(depth) %>%
  cor_test(MAG_pnps_median, trans_fudge, method = "sp") %>%
  adjust_pvalue() %>%
  select(c("cor", "p.adj"))
```



```{r}
SRF.DCM = pnps.match[pnps.match$depth %in% c("SRF", "DCM"), ]
MES = pnps.match[pnps.match$depth == "MES", ]
BAT = pnps.match[pnps.match$depth == "BAT", ]

wilcox.test(SRF.DCM$MAG_pnps_median, MES$MAG_pnps_median)
wilcox.test(MES$MAG_pnps_median, BAT$MAG_pnps_median)

median(MES$MAG_pnps_median)/median(SRF.DCM$MAG_pnps_median)
MES.shallow.test = t.test(log(MES$MAG_pnps_median), log(SRF.DCM$MAG_pnps_median))

cor.test(pnps.match$percent_trans, pnps.match$MAG_pnps_median, method = "spearman")
```


```{r}
scg_trans$depth = factor(scg_trans$depth, levels = c("SRF","DCM","MES","deep"))

scg_trans2 = scg_trans %>% filter(scg_count >= 21)
trans_fudge = min(scg_trans2$Trans_abun[scg_trans2$Trans_abun>0])

scg_trans2 = scg_trans2 %>%
  mutate(trans_abun_log = log(Trans_abun + trans_fudge),
         scg_pnps_norm = sqrt(scg_pnps_median))

scg_trans2 %>%
  ggplot(aes(x=scg_pnps_norm, y=trans_abun_log )) +
  geom_point(alpha = 0.3) +
  facet_wrap(~depth) +
  geom_smooth(method = "lm", se=F)


scg_trans=subset(scg_trans, trans_abun_norm > -4)

bin_occur = as.data.frame(table(scg_trans2$bin))
colnames(bin_occur) = c("bin", "Freq")
bin_occur = bin_occur %>%
  mutate(color_bin = ifelse(Freq > 3, as.character(bin), "other bins"))
scg_trans2 = merge(scg_trans2, bin_occur, by = "bin")

scg_trans2 %>%
  mutate(color_bin = ifelse(Trans_abun <= 0, 
                            "MAGs no transposase", color_bin)) %>%
  filter(Freq > 3) %>%
  filter(Trans_abun > 0) %>%
  ggplot(aes(x=log_scg_pnps_median, y=trans_abun_norm)) +
  facet_wrap(~depth, scale = "free_x") +
  geom_point(aes(colour = color_bin), shape=19, alpha=0.8) +
  geom_line(aes(group = color_bin, color = color_bin), 
            alpha = 0.4) + # data = subset(scg_trans2, Trans_abun > 0 & Freq > 3)
  theme_classic()
```



```{r}
scg_trans3 = merge(scg_trans2, bin_taxon[c("bin","complete genome size (Mbp)")], by = "bin")
scg_trans3 %>%
  ggplot(aes(x=log_scg_pnps_median, y=trans_abun_norm)) +
  facet_wrap(~depth) +
  geom_point(aes(color = log(`complete genome size (Mbp)`)), alpha = 0.5) +
  # scale_color_viridis(option = "D")+
  theme_classic()
```


```{r}
pnps_melt = function(pnps_df, select_col){
  return( reshape2::melt(pnps_df[select_col], id =c("bin"), value.name = c("diff")) )
}

g(defense_df, toxin_df, indi_toxin_df, GOC_toxin_df, mobilome_df, trans_df) %=% init_MAGs_pnps_depths()


sel=c("bin","gene_callers_id","SRF_ratio", "DCM_ratio", "MES_ratio", "BAT_ratio")
viz = reshape2::melt(indi_toxin_df[sel], id =c("bin","gene_callers_id"), value.name = c("diff"))
viz$cat = paste(viz$bin, viz$gene_callers_id)
viz %>%
  filter(grepl("NAT",bin)) %>%
  filter(diff < 0.2 & diff > -0.2) %>%
  ggplot(aes(x=variable, y=diff))+
  # geom_boxplot(outlier.shape = NA)+
  geom_point(aes(colour = cat), alpha = 0.3)+
  geom_line(aes(group = cat), alpha = 0.2) +
  theme_classic()


sel = c("bin", "SRF_ratio", "DCM_ratio", "MES_ratio", "BAT_ratio")
pnps_melt(toxin_df, sel) %>%
  # mutate(log_diff = log10(diff+10)) %>%
  # filter(log_diff < 1.01 & log_diff > 0.99) %>%
  filter(diff < 0.3 & diff > -0.3) %>%
  ggplot(aes(x=variable, y=diff))+
  # geom_boxplot(outlier.shape = NA)+
  geom_point(aes(colour=bin), alpha = 0.3)+
  geom_line(aes(group = bin, color = bin), alpha = 0.5) +
  theme_classic()
  # theme(legend.position="none")
```




## Find specific MAGs that are present everywhere
```{r}
scg_trans = read_csv("../MAG_pnps_redux/transposase-abun-vs-scg-pnps.csv")

scg_trans %>% 
  filter(total_count > 50 & transposase_count > 0) %>%
  group_by(bin) %>%
  summarize(count = n()) %>%
  filter(count >= 12)
```

  bin       count
1 deep-0269    12
2 deep-0293    18
3 deep-0592    14
4 IN-32        14
5 NP-15        21

These are the only ones

## Do NP-15
```{r}
MAG.reg = filter(scg_trans, total_count > 50 & bin == "deep-0592")

cor.test(MAG.reg$Trans_abun, MAG.reg$MAG_pnps_median, method = "sp")
```

