
## Oxygen DNA and RNA

```{r}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path ))
source("./init_share.R")
g(DNA_tara, RNA_tara, DNA_RNA_tara) %=% init_tara()
mala_cov <- init_mala_cov()
```

```{r}
oxy_sel_col = c("DNA_transposase", "Ocean_DNA", "Layer_DNA", "Oxygen_DNA")
oxy_to_graph = rbind(mala_cov[,oxy_sel_col], DNA_tara[,oxy_sel_col])

depth.lvl = c("SRF","DCM","MES","BAT")
oxy_to_graph = oxy_to_graph %>% 
  filter(Layer_DNA %in% depth.lvl) %>%
  mutate(Layer_DNA = factor(Layer_DNA, levels = depth.lvl))
```

```{r}
cor.test(oxy_to_graph$DNA_transposase,
         oxy_to_graph$Oxygen_DNA, method = "spearman")
```

# supplementary figure 2
```{r}
oxy_share = function(g) {
  g = g + labs(color="Ocean") +
    scale_y_continuous(trans = 'log10', 
                       labels = function(x) ifelse(x == 0, "0", x)) +
    theme_classic() +
    theme(axis.text.x = element_text(color="black"),
          axis.text.y = element_text(color="black"),
          legend.title = element_blank()) +
    xlab(expression(paste("dissolved oxygen (", mu, "mol/Kg)"))) +
    scale_color_brewer(palette="Set1") +
    stat_cor(method = "spearman", cor.coef.name = "rho",
             label.y.npc="bottom", label.x.npc = "left") +
    geom_smooth(method = "lm", se = T)
  return(g)
}

oxy_DNA = oxy_to_graph %>%
  filter(Layer_DNA != "MIX" & 
         Ocean_DNA != "Arctic" &
         !is.na(Oxygen_DNA) ) %>%
  ggplot(aes(x=Oxygen_DNA, y=DNA_transposase*100)) +
  facet_wrap(~Layer_DNA, nrow = 2) + # scales = "free"
  geom_point(aes(color = Ocean_DNA)) + 
  ylab("transposase gene abundance (%)")

oxy_share(oxy_DNA)

ggsave("out/S2_oxygen_transposase_corr.pdf", 
       plot = last_plot(), width = 7, height = 5)
```


```{r}
oxy_RNA = RNA_tara %>%
  filter(Layer_RNA != "MIX" & Ocean != "Arctic Ocean") %>%
  ggplot(aes(x=Oxygen_RNA, y=RNA_transposase * 100)) +
  facet_wrap(~Layer_RNA, nrow = 2) + # scales = "free"
  geom_point(aes(color = Ocean)) + 
  ylab("Transposase transcript abundance (%)") +
  theme() #legend.position = "none"

oxy_share(oxy_RNA)
```
